"""Shared pytest fixtures.

The strategy: tests use their own ephemeral signature database located in
`tests/_signatures/`, populated from the fixture files at session start.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path

import pytest

TESTS_ROOT = Path(__file__).resolve().parent
FIXTURES_ROOT = TESTS_ROOT / "fixtures"
TEST_SIGS_DIR = TESTS_ROOT / "_signatures"


def _sha256_of_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


@pytest.fixture(scope="session", autouse=True)
def populate_test_signatures():
    """Build a synthetic signature DB derived from fixture file hashes."""
    TEST_SIGS_DIR.mkdir(exist_ok=True, parents=True)

    # 1) Hash signatures derived from synthetic malicious fixtures.
    # Only sign the credential-pattern fixture so Layer 0 tests stay
    # deterministic; do NOT sign the pattern-chain fixture (Layer 2 tests
    # rely on Layer 0 NOT firing on it).
    target_dir = FIXTURES_ROOT / "malicious" / "synthetic_credential_pattern"
    hash_entries: list[dict] = []
    counter = 0
    if target_dir.exists():
        for path in sorted(target_dir.rglob("*")):
            if path.is_file() and path.suffix == ".py":
                counter += 1
                hash_entries.append(
                    {
                        "id": f"TEST-2026-{counter:03d}",
                        "name": f"synthetic-test-{path.parent.name}",
                        "type": "exact_hash",
                        "value": _sha256_of_file(path),
                        "category": ["test_synthetic"],
                        "severity": "critical",
                        "first_seen": "2026-01-01",
                        "references": ["https://github.com/neuregex/nodesafe/tests"],
                    }
                )

    sig_file = TEST_SIGS_DIR / "known_malware.jsonl"
    with sig_file.open("w", encoding="utf-8") as f:
        f.write("// Test signature DB — auto-generated by conftest.py\n")
        for entry in hash_entries:
            f.write(json.dumps(entry) + "\n")

    # 2) URL list
    test_urls = [
        "# Test URL list — auto-generated",
        "https://malicious-test-c2.example.invalid/webhook",
        "https://discord.com/api/webhooks/000000000000000000/TEST-EXAMPLE",
    ]
    url_file = TEST_SIGS_DIR / "malicious_urls.txt"
    url_file.write_text("\n".join(test_urls) + "\n", encoding="utf-8")

    # 3) Copy the real bundled patterns.json so Layer 2 tests run against
    # the actual production pattern set.
    repo_root = TESTS_ROOT.parent
    real_patterns = repo_root / "signatures" / "patterns.json"
    if real_patterns.exists():
        shutil.copy(real_patterns, TEST_SIGS_DIR / "patterns.json")

    # 4) Copy the top PyPI packages baseline so Layer 4 has it on disk if
    # any test instantiates `TyposquattingLayer()` without an override.
    real_top = repo_root / "signatures" / "top_pypi_packages.txt"
    if real_top.exists():
        shutil.copy(real_top, TEST_SIGS_DIR / "top_pypi_packages.txt")

    os.environ["NODESAFE_SIGNATURES_DIR"] = str(TEST_SIGS_DIR)

    yield

    os.environ.pop("NODESAFE_SIGNATURES_DIR", None)


@pytest.fixture
def benign_fixture() -> Path:
    """Path to a clean, benign fixture node."""
    return FIXTURES_ROOT / "benign" / "simple_math_node"


@pytest.fixture
def malicious_fixture() -> Path:
    """Path to a synthetic-malicious fixture node (credential-pattern)."""
    return FIXTURES_ROOT / "malicious" / "synthetic_credential_pattern"
