"""Shared pytest fixtures.

The strategy: tests use their own ephemeral signature database located in
`tests/_signatures/`, populated from the fixture files at session start.
This decouples test setup from the production signature DB and keeps the
bundled `signatures/` directory honest (only real public-disclosure entries).
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

import pytest

TESTS_ROOT = Path(__file__).resolve().parent
FIXTURES_ROOT = TESTS_ROOT / "fixtures"
TEST_SIGS_DIR = TESTS_ROOT / "_signatures"


def _sha256_of_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


@pytest.fixture(scope="session", autouse=True)
def populate_test_signatures():
    """Build a synthetic signature DB derived from fixture file hashes.

    Runs once per test session. After this, `NODEGUARD_SIGNATURES_DIR` points
    at the generated dir, so any code calling `load_hash_signatures()` or
    `load_malicious_urls()` sees the test fixture-derived data.
    """
    TEST_SIGS_DIR.mkdir(exist_ok=True, parents=True)

    # 1) Hash signatures derived from synthetic malicious fixtures
    malicious_dir = FIXTURES_ROOT / "malicious"
    hash_entries: list[dict] = []
    counter = 0
    if malicious_dir.exists():
        for path in sorted(malicious_dir.rglob("*")):
            if path.is_file() and path.suffix == ".py":
                counter += 1
                hash_entries.append(
                    {
                        "id": f"TEST-2026-{counter:03d}",
                        "name": f"synthetic-test-{path.parent.name}",
                        "type": "exact_hash",
                        "value": _sha256_of_file(path),
                        "category": ["test_synthetic"],
                        "severity": "critical",
                        "first_seen": "2026-01-01",
                        "references": ["https://github.com/neuregex/nodeguard/tests"],
                    }
                )

    sig_file = TEST_SIGS_DIR / "known_malware.jsonl"
    with sig_file.open("w", encoding="utf-8") as f:
        f.write("// Test signature DB — auto-generated by conftest.py\n")
        for entry in hash_entries:
            f.write(json.dumps(entry) + "\n")

    # 2) URL list
    test_urls = [
        "# Test URL list — auto-generated",
        "https://malicious-test-c2.example.invalid/webhook",
        "https://discord.com/api/webhooks/000000000000000000/TEST-EXAMPLE",
    ]
    url_file = TEST_SIGS_DIR / "malicious_urls.txt"
    url_file.write_text("\n".join(test_urls) + "\n", encoding="utf-8")

    # Point the loader at our test dir
    os.environ["NODEGUARD_SIGNATURES_DIR"] = str(TEST_SIGS_DIR)

    yield

    # Cleanup (optional — pytest usually doesn't need this but keeps things tidy)
    os.environ.pop("NODEGUARD_SIGNATURES_DIR", None)


@pytest.fixture
def benign_fixture() -> Path:
    """Path to a clean, benign fixture node."""
    return FIXTURES_ROOT / "benign" / "simple_math_node"


@pytest.fixture
def malicious_fixture() -> Path:
    """Path to a synthetic-malicious fixture node."""
    return FIXTURES_ROOT / "malicious" / "synthetic_credential_pattern"
